version: 2.1
jobs:
  # Build the site to store artifacts
  demo_site:
    docker:
      - image: circleci/python:3.6
      - image: circleci/ruby:2.6
    steps:
    
      # Attach the built markdown files
      - checkout
      
      # install jupyter-book
      - run:
         name: install latest jupyter book from github
         command: |
            pip install --user git+https://github.com/jupyter/jupyter-book.git
            echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV
          
      # build the site
      - run:
          name: Build site markdown
          command: make book

      # Build the site's HTML w/ the base_url for CircleCI artifacts
      - build_site:
          build_args: --baseurl /0/html/

      # Tell Circle to store the documentation output in a folder that we can access later
      - store_artifacts:
          path: _site
          destination: html

      - store_artifacts:
          path: _build
  
  install_jupyter_book:
    docker:
      - image: circleci/python:3.6
    steps:
      - run: echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV
      - run: 
         name: install jupyter book from github
         command: sudo apt-get update && pip install --user git+https://github.com/jupyter/jupyter-book.git



# Tell CircleCI to use this workflow when it builds the site
workflows:
  version: 2
  default:
    jobs:
      - install_jupyter_book:
          filters:
            branches:
              ignore:
                - gh-pages
      - demo_site:
          requires:
            - install_jupyter_book
          filters:
            branches:
              ignore:
                - gh-pages


commands:
  build_site:
    description: "Build the site with Jekyll"
    parameters:
      build_args:
        type: string
        default: ""
    steps:
      - checkout
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "jupyter_book/book_template/Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run: gem install bundler
      - run: bundle install

      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Build the website
          command: bundle exec jekyll build << parameters.build_args >>
