name: HTML-Preview

on:
  repository_dispatch:
    types: [preview-command]

jobs:
  report_artifacts:
    runs-on: ubuntu-latest
    name: Comment preview url
    steps:
         
      - name: Get the target branch name
        id: getbranch
        run: |
          branch=${{ github.event.client_payload.slash_command.branch }}
          if [[ -z "$branch" ]]; then branch="master"; fi
          echo ::set-output name=branch::$branch
        
      - name: Get preview url using CircleCI REST API
        id: geturl
        run: |
          site=`curl -s -H'Circle-Token: ${{ secrets.CIRCLE_CI_ACCESS_TOKEN }}' "https://circleci.com/api/v1.1/project/github/joergbrech/Modellbildung-und-Simulation/latest/artifacts?branch=${{ steps.getbranch.outputs.branch }}&filter=successful" | grep '0/html/intro.html' | cut -d \" -f4`
          echo $site
          echo "::set-output name=site::$site"
          
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Hello @${{ github.event.client_payload.github.actor }}!
            [Click here to see a preview of the site](${{ steps.geturl.outputs.site }})
